#Este fichero contendrá las constantes que usaremos a lo largo de la practica
#por conveniencia REVISAR la guia de estilos de python https://www.python.org/dev/peps/pep-0008/
#para que todos sigamos un estilo más o menos común:
import helpers.modelFileHelper as mh

#Clave para acceder al file helper del fichero Train
TRAIN_KEY = "train"
# Clave para acceder al file helper del fichero Test
TEST_KEY = "test"
# Diccionario que contiene los ficheros CSV bajo las claves. Pueden ser accedidos mediante las claves train y test 
CSV_FILES = { TRAIN_KEY : mh.ModelFileHelper("data_sources/train.csv"), TEST_KEY :   mh.ModelFileHelper("data_sources/test.csv")} 
# Diccionario que contiene todos los posibles lenguajes para transcribirlos a un valor numérico.
LANGUAGES = {
'Bengali':1,
'Hindi':2,
'Tamil':3,
'Malayalam':4,
'Chattisgari':5,
'Telugu':6,
'Marathi':7,
'Nepali':8,
'Rajasthani':9,
'Marathi&Hindi':10,
'Assamese':11,
'Telugu&Kannada':12,
'Punjabi':13,
'Kannada':14,
'Oriya':15,
'English':16,
'None':17,
'Gujarati':18,
'Kokborok':19,
'Gujarati&Marathi':20,
'Manipuri':21,
'Hindi&Oriya':22,
'Hindi&Marathi':23,
'Urdu':24,
'Mewari':25,
'Hindi&Rajasthani':26,
'Hindi&Punjabi':27,
'Thadou':28,
'Punjabi&Hindi':29,
'Konkani':30,
'Govan':31,
'Konkani&Hindi':32,
'TribalLanguage':33,
'Aadiwasi':34,
'Urdu,Kannada&Hindi':35,
'sanskrit':36,
'Hindi&Urdu':37,
'Bhojpuri':38,
'Meitei':39,
'Karbi':40,
'Arbi':41,
'Haryanvi':42,
'Kannada&Urdu':43,
'Dehati':44,
'Kannada&Telugu':45,
'Marathi&Kannada':46,
'Hindi&Gujarati':47,
'Hindi,Oriya&Bengali':48,
'Hindi&Kannada':49,
'Oriya,Hindi&Bengali':50,
'Santhali':51,
'Oriya&Hindi':52,
'Rabha':53,
'Hindi,Marathi&Gujarati':54,
'AssameseandHindi':55,
'Bengali':56,
'Hindi':57,
'Tamil':58,
'Malayalam':59,
'Chattisgari':60,
'Telugu':61,
'Marathi':62,
'Rajasthani':63,
'Marathi&Hindi':64,
'Assamese':65,
'Punjabi':66,
'Kannada':67,
'Oriya':68,
'Gujarati':69,
'None':70,
'Kokborok':71,
'Manipuri':72,
'Gujarati&Marathi':73,
'English':74,
'Hindi&Oriya':75,
'Bhojpuri':76,
'Hindi&Marathi':77,
'Urdu':78,
'Sanskrit':79,
'Mundri':80,
'Urdu&Kannada':81,
'marwadi':82,
'Thadou':83,
'Urdu&Hindi':84,
'Konkani':85,
'Jharkhandi':86,
'English,Hindi&Bengali':87,
'Konkani&Hindi':88,
'TribalLanguage':89,
'Meitei':90,
'Aadiwasi':91,
'Chhetriyabhasha':92,
'Hindi&Urdu':93,
'Nepali':94,
'Arbi':95,
'Punjabi&Hindi':96,
'Boro':97,
'Haryanvi':98,
'Kannada&Telugu':99,
'Hindi&Gujarati':100,
'Kannada&Urdu':101,
'Hindi,Oriya&Bengali':102,
'Hindi&Kannada':103,
'Marathi&Kannada':104,
'Oriya,Hindi&Bengali':105,
'Hindi&Punjabi':106,
'Govan':107,
'Santhali':108,
'Oriya&Hindi':109,
'Rabha':110,
'Telugu&Kannada':111,
'Hindi,Marathi&Gujarati':112}
