#Este fichero contendrá las constantes que usaremos a lo largo de la practica
#por conveniencia REVISAR la guia de estilos de python https://www.python.org/dev/peps/pep-0008/
#para que todos sigamos un estilo más o menos común:
import helpers.modelFileHelper as mh

#Clave para acceder al file helper del fichero Train
TRAIN_KEY = "train"
# Clave para acceder al file helper del fichero Test
TEST_KEY = "test"
# Diccionario que contiene los ficheros CSV bajo las claves. Pueden ser accedidos mediante las claves train y test 
CSV_FILES = { TRAIN_KEY : mh.ModelFileHelper("data_sources/train.csv"), TEST_KEY :   mh.ModelFileHelper("data_sources/test.csv")} 
# Diccionario que contiene todos los posibles lenguajes para transcribirlos a un valor numérico.
LANGUAGES = {
'Bengali':1,
'Hindi':2,
'HIndi':2,
'Tamil':3,
'Malayalam':4,
'Chattisgari':5,
'Telugu':6,
'Marathi':7,
'Nepali':8,
'Rajasthani':9,
'Marathi & Hindi':10,
'Assamese':11,
'Telugu & Kannada':12,
'Punjabi':13,
'Kannada':14,
'Oriya':15,
'English':16,
'None':17,
'Gujarati':18,
'Kokborok':19,
'Gujarati & Marathi':20,
'Hindi & Oriya':22,
'Hindi & Marathi':23,
'Urdu':24,
'Mewari':25,
'Hindi & Rajasthani':26,
'Hindi & Punjabi':27,
'Thadou':28,
'Punjabi & Hindi':29,
'Konkani':30,
'Govan':31,
'Konkani & Hindi':32,
'TribalLanguage':33,
'Aadiwasi':34,
'Urdu, Kannada & Hindi':35,
'sanskrit':36,
'Hindi & Urdu':37,
'Bhojpuri':38,
'Meitei':39,
'Karbi':40,
'Arbi':41,
'Haryanvi':42,
'Kannada & Urdu':43,
'Dehati':44,
'Kannada & Telugu':45,
'Marathi & Kannada':46,
'Hindi & Gujarati':47,
'Hindi, Oriya & Bengali':48,
'Hindi & Kannada':49,
'Oriya, Hindi & Bengali':50,
'Santhali':51,
'Oriya & Hindi':52,
'Rabha':53,
'Hindi, Marathi & Gujarati':54,
'Assamese and Hindi':55,
'Manipuri':72,
'Sanskrit':79,
'Mundri':80,
'Urdu & Kannada':81,
'marwadi':82,
'Urdu & Hindi':84,
'Jharkhandi':86,
'English, Hindi & Bengali':87,
'Tribal Language':89,
'Chhetriya bhasha':92,
'Boro':97,
'Marwadi':113}